import type { Metadata } from "next";
import Link from "next/link";
import { requirePageUser } from "@/features/auth/current-user";
import { canUpdateTaskStatus, hasPermission } from "@/features/auth/permissions";
import { getCurrentWedding } from "@/features/weddings/service";
import { listTasks, taskEventOptions } from "@/features/tasks/service";
import { deadlineLabel, isOverdue, priorityLabels, statusLabels } from "@/features/tasks/format";
import { TASK_PRIORITIES, TASK_STATUSES } from "@/types/domain";
import { TaskStatusControl } from "@/components/tasks/task-status-control";
import { Icon } from "@/components/marketing/icon";
import { OverdueBadge, PriorityBadge, StatusBadge, TaskIllustration, primaryAction, secondaryAction, taskIdeas } from "@/components/tasks/task-ui";

export const metadata: Metadata = { title: "Wedding checklist", robots: { index: false, follow: false } };
export default async function Page({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const user = await requirePageUser(), params = await searchParams;
  const search = new URLSearchParams();
  for (const key of ["page", "status", "priority", "eventId", "overdue", "search"]) if (typeof params[key] === "string" && params[key]) search.set(key, params[key]);
  const [wedding, result, events] = await Promise.all([getCurrentWedding(), listTasks(search), taskEventOptions()]);
  const manage = hasPermission(user.role, "tasks:manage"), couple = `${wedding.groomName} & ${wedding.brideName}`;
  const { counts, pagination } = result, percent = counts.total ? Math.round(counts.COMPLETED / counts.total * 100) : 0;
  const eventNames = new Map(events.map(event => [event.id, event.name]));
  function href(key: string, value: string) { const next = new URLSearchParams(search); next.delete("page"); if (value) next.set(key, value); else next.delete(key); return `/tasks?${next}`; }
  const filterClass = "min-h-11 min-w-0 rounded-xl border border-transparent bg-surface-container-low px-3 py-2 text-sm focus:border-outline-variant";
  const ideaIcons = ["photo_camera", "group", "checklist"] as const;
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-[11px] font-semibold uppercase tracking-widest text-on-surface-variant">Wedding workspace <span aria-hidden="true">·</span> {couple}</p><h1 className="font-display-md text-[32px] leading-tight text-primary sm:text-4xl">Wedding checklist</h1><p className="mt-3 text-sm text-on-surface-variant">Keep every family celebration and preparation on track, together.</p></div>{manage && counts.total > 0 && <Link href="/tasks/new" className={`${primaryAction} self-start sm:shrink-0`}><Icon name="add" />Add Task</Link>}</div>
    {params.deleted === "1" && <p role="status" className="rounded-xl bg-secondary-container p-4 text-sm">Task deleted. Your other wedding plans have been preserved.</p>}
    {counts.total > 0 && <section aria-labelledby="progress-title" className="space-y-5 rounded-2xl bg-surface-container-lowest p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 id="progress-title" className="mb-2 text-[11px] font-semibold uppercase tracking-widest text-on-surface-variant">Overall completion</h2><p><span className="font-display-md text-xl text-primary">{counts.COMPLETED} of {counts.total}</span> <span className="text-xs text-on-surface-variant">tasks completed</span></p></div><p className="rounded-full bg-primary-fixed/40 px-3 py-1 text-xs font-semibold text-primary">{percent}% complete</p></div><div role="progressbar" aria-label="Task completion" aria-valuemin={0} aria-valuemax={100} aria-valuenow={percent} className="h-2 overflow-hidden rounded-full bg-primary-fixed/50"><div className="h-full rounded-full bg-primary-container transition-all" style={{ width: `${percent}%` }} /></div><dl className="grid grid-cols-2 gap-3 sm:grid-cols-4">{(["COMPLETED", "IN_PROGRESS", "TODO", "overdue"] as const).map(key => <div key={key} className={`rounded-xl px-4 py-3 ${key === "overdue" ? "bg-error-container/70 text-on-error-container" : "bg-surface-container-low"}`}><dd className="text-xl font-semibold">{counts[key]}</dd><dt className="mt-1 text-xs">{key === "overdue" ? "Overdue" : statusLabels[key]}</dt></div>)}</dl></section>}
    {counts.total === 0 ? <section className="rounded-[20px] bg-surface-container-lowest px-5 py-12 text-center shadow-sm sm:px-10 sm:py-16"><div className="mx-auto flex max-w-2xl flex-col items-center"><TaskIllustration /><h2 className="mt-5 font-display-md text-[28px] text-primary">Your wedding checklist starts here</h2><p className="mt-3 max-w-lg text-sm leading-relaxed text-on-surface-variant">Bring all the little preparations together in one shared place. Add your first task and start planning for {couple}.</p>{manage && <><Link href="/tasks/new" className={`${primaryAction} mt-6`}><Icon name="add" />Add your first task</Link><div className="mt-10 w-full"><h3 className="mb-4 text-[11px] font-semibold uppercase tracking-widest text-on-surface-variant">A little inspiration to get started</h3><div className="grid gap-3 sm:grid-cols-3">{taskIdeas.map((title, index) => <Link key={title} href={`/tasks/new?title=${encodeURIComponent(title)}`} className="flex flex-col items-start gap-4 rounded-xl bg-surface-container-low p-5 text-left transition-colors hover:bg-primary-fixed/40"><Icon name={ideaIcons[index]} className="text-2xl text-primary-container" /><span className="text-sm font-semibold">{title}</span><span className="text-xs text-primary">Create task <span aria-hidden="true">→</span></span></Link>)}</div></div></>}</div></section> : <section className="overflow-hidden rounded-2xl bg-surface-container-lowest shadow-sm">
      <div className="space-y-4 border-b border-outline-variant/30 p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><nav aria-label="Task views" className="flex flex-wrap gap-1">{["", ...TASK_STATUSES].map(status => <Link key={status} href={href("status", status)} aria-current={(search.get("status") || "") === status ? "page" : undefined} className={`rounded-full px-3 py-2 text-xs font-semibold ${(search.get("status") || "") === status ? "bg-primary-fixed/50 text-primary" : "text-on-surface-variant hover:bg-surface-container-low"}`}>{status ? statusLabels[status as keyof typeof statusLabels] : "All"} <span className="ml-1">{status ? counts[status as keyof typeof statusLabels] : counts.total}</span></Link>)}</nav><div className="flex flex-wrap items-center gap-3"><Link href={href("overdue", search.get("overdue") === "true" ? "" : "true")} aria-current={search.get("overdue") === "true" ? "page" : undefined} className={`inline-flex min-h-11 items-center gap-1 rounded-full px-3 text-xs ${search.get("overdue") === "true" ? "bg-error text-on-error" : "bg-error-container text-on-error-container"}`}><Icon name="warning" />Overdue ({counts.overdue})</Link><Link href="/tasks" className="text-xs text-on-surface-variant underline">Clear filters</Link></div></div>
        <form key={search.toString()} action="/tasks" method="get" aria-label="Task filters" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-[2fr_1fr_1fr_auto]">{search.get("status") && <input type="hidden" name="status" value={search.get("status")!} />}{search.get("overdue") === "true" && <input type="hidden" name="overdue" value="true" />}<input name="search" aria-label="Search tasks" placeholder="Search by task title…" maxLength={120} defaultValue={search.get("search") || ""} className={filterClass} /><select name="eventId" aria-label="Filter by event" defaultValue={search.get("eventId") || ""} className={filterClass}><option value="">All events</option><option value="wedding-wide">Wedding-wide</option>{events.map(event => <option key={event.id} value={event.id}>{event.name}</option>)}</select><select name="priority" aria-label="Filter by priority" defaultValue={search.get("priority") || ""} className={filterClass}><option value="">All priorities</option>{TASK_PRIORITIES.map(priority => <option key={priority} value={priority}>{priorityLabels[priority]}</option>)}</select><button className={secondaryAction} type="submit">Apply filters</button></form>
      </div>
      <div className="hidden grid-cols-[2fr_1fr_1.4fr_.6fr_.8fr_auto] gap-4 bg-surface-container-low/60 px-6 py-3 text-[11px] text-on-surface-variant xl:grid" aria-hidden="true"><span>Task</span><span>Related event</span><span>Deadline (IST)</span><span>Priority</span><span>Status</span><span>Action</span></div>
      {result.tasks.length === 0 ? <div className="p-10 text-center"><h2 className="font-display-md text-2xl text-primary">No tasks match these filters</h2><p className="mt-3 text-sm text-on-surface-variant">Try another search or clear the filters to see your checklist.</p><Link href="/tasks" className={`${secondaryAction} mt-5`}>View all tasks</Link></div> : result.tasks.map(task => <article key={task.id} className="grid min-w-0 gap-4 border-b border-outline-variant/20 p-5 last:border-b-0 sm:p-6 xl:grid-cols-[2fr_1fr_1.4fr_.6fr_.8fr_auto] xl:items-center"><div className="min-w-0"><div className="flex items-start gap-2"><div className="shrink-0"><div>{canUpdateTaskStatus(user, task) ? <TaskStatusControl compact id={task.id} title={task.title} status={task.status} /> : <Icon name={task.status === "COMPLETED" ? "check_circle" : "radio_button_unchecked"} className="mt-0.5 shrink-0 text-primary-container" />}</div></div><h2 className="min-w-0 break-words text-sm font-semibold"><Link href={`/tasks/${task.id}`} className="hover:text-primary">{task.title}</Link></h2></div>{task.description && <p className="ml-6 mt-2 line-clamp-2 break-words text-xs leading-relaxed text-on-surface-variant">{task.description}</p>}</div><div className="min-w-0"><p className="mb-1 text-[11px] text-on-surface-variant xl:hidden">Related event</p><span className="inline-block max-w-full break-words rounded-full bg-surface-container-low px-3 py-1 text-xs">{task.eventId ? eventNames.get(task.eventId) || "Event unavailable" : "Wedding-wide"}</span></div><div className="space-y-2"><p className="text-xs text-on-surface-variant">{deadlineLabel(task.dueAt)}</p>{isOverdue(task, result.asOf) && <OverdueBadge />}</div><div className="flex items-center justify-between gap-3 xl:contents"><PriorityBadge priority={task.priority} /><div><StatusBadge status={task.status} /></div></div><Link href={`/tasks/${task.id}`} className="inline-flex min-h-11 items-center justify-center rounded-full bg-surface-container-low px-3 py-2 text-xs font-semibold hover:bg-surface-container">View details<span className="sr-only"> for {task.title}</span></Link></article>)}
      <div className="flex flex-wrap items-center justify-between gap-3 border-t border-outline-variant/30 px-5 py-4 text-xs text-on-surface-variant"><p>Showing {result.tasks.length} of {pagination.total} tasks · Newest first</p>{pagination.pages > 1 && <nav aria-label="Tasks pagination" className="flex items-center gap-3">{pagination.page > 1 && <Link href={href("page", String(pagination.page - 1))} className={secondaryAction}>Previous</Link>}<span>Page {pagination.page} of {pagination.pages}</span>{pagination.page < pagination.pages && <Link href={href("page", String(pagination.page + 1))} className={secondaryAction}>Next</Link>}</nav>}</div>
    </section>}
  </div>;
}
