import type { Metadata } from "next";
import Link from "next/link";
import { requirePageUser } from "@/features/auth/current-user";
import { hasPermission } from "@/features/auth/permissions";
import { getPageGuest } from "@/features/guests/page-data";
import { guestTimestamp } from "@/features/guests/format";
import { AttendanceBadge, BackToGuests, GuestAvatar, guestCard, GuestNotice, GuestReadOnly, secondaryAction } from "@/components/guests/guest-ui";
import { DeleteGuestButton } from "@/components/guests/delete-guest-button";
export const metadata: Metadata = { title: "Guest details", robots: { index: false, follow: false } };
export default async function Page({ params, searchParams }: { params: Promise<{ guestId: string }>; searchParams: Promise<{ saved?: string }> }) {
  const user = await requirePageUser();
  const [guest, search] = await Promise.all([getPageGuest((await params).guestId), searchParams]);
  const manage = hasPermission(user.role, "guests:manage");
  return <div className="mx-auto max-w-6xl space-y-6"><BackToGuests />{!manage && <GuestReadOnly />}{(search.saved === "created" || search.saved === "updated") && <p role="status" className="rounded-xl bg-secondary-container p-4 text-sm">Guest {search.saved === "created" ? "created" : "updated"} successfully.</p>}
    <section className={`${guestCard} flex flex-wrap items-center justify-between gap-5`}><div className="flex w-full min-w-0 items-center gap-4 sm:w-auto sm:flex-1 sm:basis-64"><GuestAvatar name={guest.name} large /><div className="min-w-0"><p className="break-words text-xs uppercase tracking-wide text-secondary">{guest.familyName || "No family name"}</p><h1 className="mt-2 break-words font-display-md text-3xl text-primary sm:text-4xl">{guest.name}</h1><div className="mt-3"><AttendanceBadge status={guest.rsvpStatus} /></div></div></div>{manage && <div className="flex flex-wrap gap-3"><Link href={`/guests/${guest.id}/edit`} className={secondaryAction}>Edit guest</Link><DeleteGuestButton guest={guest} /></div>}</section>
    <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(0,1fr)]"><div className="min-w-0 space-y-6"><section className={guestCard}><h2 className="text-xl font-semibold">Contact Information</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div className="min-w-0 rounded-xl bg-surface-container-low p-4"><dt className="text-xs uppercase text-secondary">Phone number</dt><dd className="mt-3 break-all text-sm font-semibold text-primary">{guest.phone ? <a href={`tel:${encodeURIComponent(guest.phone)}`} className="underline">{guest.phone}</a> : "Not provided"}</dd></div><div className="min-w-0 rounded-xl bg-surface-container-low p-4"><dt className="text-xs uppercase text-secondary">Email address</dt><dd className="mt-3 break-all text-sm font-semibold text-primary">{guest.email ? <a href={`mailto:${encodeURIComponent(guest.email)}`} className="underline">{guest.email}</a> : "Not provided"}</dd></div><div className="min-w-0 rounded-xl bg-surface-container-low p-4 sm:col-span-2"><dt className="text-xs uppercase text-secondary">Family name</dt><dd className="mt-2 break-words text-sm">{guest.familyName || "Not provided"}</dd></div></dl><p className="mt-4 rounded-xl bg-surface-container-low p-3 text-xs leading-relaxed text-secondary">Phone and email links open your default apps directly. Invitation sending and guest self-service RSVP are coming soon.</p></section><section className={guestCard}><h2 className="text-xl font-semibold">Notes</h2><p className="mt-5 whitespace-pre-wrap break-words rounded-xl bg-surface-container-low p-4 text-sm leading-relaxed text-secondary">{guest.notes || "Not provided"}</p></section></div>
    <div className="min-w-0 space-y-6"><section className={guestCard}><h2 className="text-xl font-semibold">Attendance Breakdown</h2><div className="mt-5 rounded-xl bg-surface-container-low p-4"><p className="mb-3 text-xs uppercase text-secondary">Attendance status</p><AttendanceBadge status={guest.rsvpStatus} /><p className="mt-3 text-xs text-secondary">Maintained manually by organizers.</p></div><dl className="mt-4 grid grid-cols-2 gap-4">{([["Number invited", guest.numberInvited, "People covered by this guest entry."], ["Number attending", guest.numberAttending, "People confirmed for this guest entry."]] as const).map(([label, value, help]) => <div key={label} className="min-w-0 rounded-xl bg-surface-container-low p-4"><dt className="text-xs text-secondary">{label}</dt><dd className={`mt-3 break-words text-primary ${value == null ? "text-sm" : "font-display-md text-3xl"}`}>{value ?? "Not provided"}</dd><p className="mt-2 text-xs leading-relaxed text-secondary">{help}</p></div>)}</dl></section>
    <section className={guestCard}><h2 className="text-xl font-semibold">Record Metadata</h2><dl className="mt-5 space-y-5 text-xs">{([["Created", guest.createdAt], ["Last updated", guest.updatedAt], ["Attendance last updated", guest.rsvpUpdatedAt]] as const).map(([label, value]) => <div key={label} className="flex flex-wrap justify-between gap-2"><dt className="text-secondary">{label}</dt><dd>{guestTimestamp(value)}</dd></div>)}</dl></section></div></div><GuestNotice /></div>;
}
