import type { Metadata } from "next";
import Link from "next/link";
import { getPageActivity } from "@/features/activities/page-data";
import { activityTimestamp } from "@/features/activities/format";
import { ActivityIcon, activityCard, ActivityNotice, BackToActivities, secondaryAction, SourceBadge } from "@/components/activities/activity-ui";
import { DeleteActivityButton } from "@/components/activities/delete-activity-button";
export const metadata: Metadata = { title: "Update details", robots: { index: false, follow: false } };
export default async function Page({ params, searchParams }: { params: Promise<{ activityId: string }>; searchParams: Promise<{ saved?: string }> }) {
  const [activity, search] = await Promise.all([getPageActivity((await params).activityId), searchParams]);
  const automatic = activity.sourceType === "SYSTEM";
  return <div className="mx-auto max-w-6xl space-y-6"><BackToActivities />{(search.saved === "created" || search.saved === "updated") && <p role="status" className="rounded-xl bg-secondary-container p-4 text-sm">Update {search.saved === "created" ? "created" : "saved"} successfully.</p>}
    <section className={`${activityCard} space-y-5`}><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex w-full min-w-0 items-start gap-4 sm:w-auto sm:flex-1 sm:basis-64"><ActivityIcon activity={activity} /><div className="min-w-0"><SourceBadge source={activity.sourceType} /><h1 className="mt-3 break-words font-display-md text-3xl text-primary sm:text-4xl">{activity.title}</h1></div></div>{activity.canModify && <div className="flex flex-wrap gap-3"><Link href={`/activities/${activity.id}/edit`} className={secondaryAction}>Edit update</Link><DeleteActivityButton activity={activity} /></div>}</div>
      <div className="flex flex-wrap gap-x-5 gap-y-3 text-xs text-secondary"><p className="break-words">{automatic ? "Recorded by" : "Author"}: {activity.authorName}</p><time dateTime={activity.createdAt}>{activityTimestamp(activity.createdAt)}</time>{activity.activityType && <p className="break-words">Category: {activity.activityType}</p>}</div>
    </section>
    {automatic && <p className="rounded-xl bg-surface-container-low p-5 text-sm leading-relaxed text-secondary">Automatically recorded by Make My Marriage. This update cannot be edited or deleted.</p>}
    {!automatic && !activity.canModify && <p className="rounded-xl bg-surface-container-low p-5 text-sm text-secondary">Only the author, owner or admins can edit or delete this manual update.</p>}
    <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(0,1fr)]"><section className={activityCard}><h2 className="text-xl font-semibold">{automatic ? "Activity details" : "Description"}</h2><p className="mt-5 whitespace-pre-wrap break-words text-sm leading-relaxed text-secondary">{activity.description || "No description provided."}</p></section><div className="min-w-0 space-y-6"><section className={activityCard}><h2 className="text-lg font-semibold">Related event</h2><div className="mt-4 rounded-xl bg-surface-container-low p-4">{activity.event ? <Link href={`/events/${activity.event.id}`} className="inline-flex min-h-11 items-center break-words text-sm font-semibold text-primary underline">{activity.event.name}</Link> : <><p className="font-semibold text-primary">Wedding-wide</p><p className="mt-2 text-xs text-secondary">No specific event linked.</p></>}</div></section><section className={activityCard}><h2 className="text-lg font-semibold">Update information</h2><dl className="mt-5 space-y-4 text-xs">{[["Source", automatic ? "Automatic update" : "Manual update"], [automatic ? "Recorded by" : "Author", activity.authorName], ["Created", activityTimestamp(activity.createdAt)], ["Category", activity.activityType || "Not provided"]].map(([label, value]) => <div key={label} className="flex flex-wrap justify-between gap-2"><dt className="text-secondary">{label}</dt><dd className="max-w-full break-words">{value}</dd></div>)}</dl></section></div></div><ActivityNotice />
  </div>;
}
